config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/article/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <article>
        <h1>
          <%= @article.title %>
          <small>
            <%= link_to article_path(@article), method: :delete do %>
              <i class="fa fa-trash"></i>
            <% end %>
            <%= link_to edit_article_path(@article) do %>
              <i class="fa fa-edit"></i>
            <% end %>
          </small>
        </h1>

        <hr>

      </article>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', article: @article%>

app/views/articles/index.html.erb
<h1>Wikinimous</h1>
<% @articles.each do |article| %>
    <article>
    <h2>
      <%= link_to article.title, article_path(article) %>
      <%= link_to article_path(article), method: :delete do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </h2>
    <p><%= article.content %></p>
  </article>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article%>

app/views/articles/show.html.erb
        <h1>
          <%= @article.title %>
          <small>
            <%= link_to article_path(@article), method: :delete do %>
              <i class="fa fa-trash"></i>
            <% end %>
            <%= link_to edit_article_path(@article) do %>
              <i class="fa fa-edit"></i>
            <% end %>
          </small>
        </h1>

        <hr>
        <p><%= @article.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>